### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by keppelen** [keppelen/react-facebook-login#1]
add tests with [Jasmine](http://jasmine.github.io/) and [karma](http://karma-runner.github.io/0.13/index.html)

**Comment by sachinvelaga** [comment]
Can i have a demo working with code using this.

**Comment by keppelen** [comment]
Of course :)
http://descomplica.com.br/cadastro

**Comment by sachinvelaga** [comment]
Can i have a look at the code .. or can u write a nice tutorial for this. There are no  good  tutorials for we learners ..

**Comment by keppelen** [comment]
@sachinvelaga Sorry i not tutorial about this. But you can read the [README](https://github.com/keppelen/react-facebook-login/blob/master/README.md) for more details
