### ISSUE TITLE
How to Setup

### ISSUE THREAD

**Issue by MrLoh** [keppelen/react-facebook-login#103]
Hi, this looks great. But I don't get how to set it up/ I can't get the demo to run locally, nor set it up in my own app, the button always looks disabled and doesn't react at all. What do I have to setup on the facebook site. Is this still working?

**Comment by MrLoh** [comment]
When I try to use it. `isSdkLoaded` in the state somehow stays `false`. But in my console `window.FB` is assigned. Seems like something is going wrong there maybe?

**Comment by keppelen** [comment]
resolve in new version https://www.npmjs.com/package/react-facebook-login
