### ISSUE TITLE
Response Type Code ?

### ISSUE THREAD

**Issue by Stefflan00** [keppelen/react-facebook-login#116]
So I want to use React as Frontend with some API Backend. To be secure as possible I read that i should use code response instead of access token.

As I look in the official documentation https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow.
I wonder if there will be response_type: code support in the future?

**Comment by keppelen** [comment]
the callback function return this objc
```json
{
  "accessToken": "EAAPeEvT9YHgBAN01ZAymorOo9bcoY8ZB5V...",
  "expiresIn": 5733,
  "id": "10203478808561969",
  "name": "Giovanni Keppelen",
  "signedRequest": "4pjbmxKWSqxg8sWEU-MrhZM0gndhebPcOlDncf...",
  "userID": "10203478808561969",
}

```

**Comment by Stefflan00** [comment]
@keppelen 
"When code is received, it has to be exchanged for an access token using an endpoint. The call will need to be server-to-server, since it involves your app secret. (Your app secret should never end up in client code.)" So i do not want to receive the "accessToken" i want to receive the "code" so i can change it serverside for a AccessToken.

**Comment by keppelen** [comment]
in you back-end you need request facebook passing `accessToken` to verify is valid.

**Comment by Stefflan00** [comment]
@keppelen i refer to the Facebook documentation:
"response_type. Determines whether the response data included when the redirect back to the app occurs is in URL parameters or fragments. See the Confirming Identity section to choose which type your app should use. This can be one of:
code. Response data is included as URL parameters and contains code parameter (an encrypted string unique to each login request). This is the default behavior if this parameter is not specified. It's most useful when your server will be handling the token." => So if we do not set the "response_type" we will get a code. We have now to build an accessToken serverside and not validate it. In this scenario we protect our App from third party attacks (might be spamming in facebook if we have permissions to post etc ). So the Client has not a Facebook access token at all. I know now how to implement it and would do a pull request if that is ok with you.

**Comment by ebasic** [comment]
@maier-stefan  How to obtain access code on clientside, in React? At the moment, I have only above mentioned response from Facebook including accessToken (I use react-facebook-login package and pass callback function to it to get this response). But I need somehow to implement that functionality with redirect uri and obtain access code.
