### ISSUE TITLE
NODE_ENV

### ISSUE THREAD

**Issue by mitalimn** [keppelen/react-facebook-login#117]
> NODE_ENV=development node_modules/.bin/webpack-dev-server --config webpack.config.js

'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-facebook@3.5.0 start: `NODE_ENV=development node_modules/.bin/webpack-dev-server --config webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-facebook@3.5.0 start script 'NODE_ENV=development node_modules/.bin/webpack-dev-server --config webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-facebook package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=development node_modules/.bin/webpack-dev-server --config webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-facebook
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-facebook
npm ERR! There is likely additional logging output above.

**Comment by Sublunarwind** [comment]
If you use a windows system, in **package.js** change those line inside **"scripts": {}** to:

`"start": "SET NODE_ENV=development & node_modules\\.bin\\webpack-dev-server --config webpack.config.js",
    "bundle": "SET NODE_ENV=production & node_modules\\.bin\\webpack -p --config webpack.config.dist.js",
    "test": "node_modules\\.bin\\eslint src\\**\\*.js"`
