### ISSUE TITLE
Don't check in minified javascript

### ISSUE THREAD

**Issue by brysgo** [keppelen/react-facebook-login#12]
It is a security risk using a library to handle something sensitive like login when it has been obfuscated on someone else's machine.

**Comment by keppelen** [comment]
@brysgo i don't understand your question.

**Comment by brysgo** [comment]
I'm simply concerned with the fact that by checking in minified code, instead of say generating it post install, or even not minifying it, you are providing a vector of attack for a malicious developer.

Someone could contribute a nice bugfix, and sneak something into the minified code.

**Comment by Elyx0** [comment]
@brysgo is right. You might want to read as an example https://zyan.scripts.mit.edu/blog/backdooring-js/

**Comment by brysgo** [comment]
@Elyx0 - Really cool post, I'm afraid the vulnerability I am pointing out is much simpler + less clever than that.

@keppelen - Say I wanted to steal all your user's auth tokens. I could write in a line to send those tokens to my server. Now, obviously you and everyone else looking at the code would see this.

So to hide it, I can make a simple fix to your repo, minify it along with my malicious code, and submit a pull request. Now surely someone would notice that their website was communicating with a strange server? One could simply dress it up as a cdn of a js library that everyone uses.

**Comment by brysgo** [comment]
Sweep it under the rug :) I'm sure no one will notice when you steal their passwords.
