### ISSUE TITLE
Making it work on mobile

### ISSUE THREAD

**Issue by boriswexler** [keppelen/react-facebook-login#124]
Hi,
I have the component set up and working well, however on mobile it doesn't work at all - the Facebook popup never appears, and it redirects me to my login and appends a code=[some_code]&state=facebookdirect string of parameters to the url. It doesn't seem like the provided callback is ever called.

I read through the documentation and related issues - could someone clarify how to use the component on mobile? Am I supposed to set a redirectURI? If so is that URI then in turn meant to pass the authetication data to the backend and log the user in? For reference here is my current code:
`<FacebookLogin
                                    appId='998508906904354'
                                    autoLoad={false}
                                    fields='name,email,picture'
                                    callback={this.responseFacebook.bind(this)}
                                    icon="fa-facebook"
                                    size="small"
                                    cssClass="button-facebook-login"
                                    textButton={strings.login_facebook}
                                    isMobile={true}
                                />`
Thanks in advance!

**Comment by superplussed** [comment]
@boriswexler were you able to get this working?

**Comment by boriswexler** [comment]
I have not so far. Tried a few ways but the facebook pop up never shows and
it just redirects to the original URL with additional parameters. Any help
would be appreciated.

**Comment by TarikHuber** [comment]
I had the same problem.
Have you tried to set `disableMobileRedirect={true}`?

The param is not in the docu but If you inspect the code you can see that if it detects that the device is mobile and this prop is set to `false` (default value) it won't call the usual login function but another one. The other one uses some more complicated way so it is working fine when it redirects you and gives you "code" and "state". You should then send another response to facebook with your app secret to get the user data. tl:dr: seting disableMobileRedirect to true forces it to use the same login method that it uses in non mobile devices. 

I don't know if it has any bad sides but on my mobile device it works for now :)

Here is a working example: https://github.com/TarikHuber/react-most-wanted

**Comment by boriswexler** [comment]
Thank you, that worked great!

**Comment by Abhijeetjaiswalit** [comment]
any idea why it is showing this warning ? 

Warning: Failed propType: Invalid prop `isMobile` of type `array` supplied to `t`, expected `boolean`. Check the render method of `Login`.

**Comment by TarikHuber** [comment]
@Abhijeetjaiswalit you variable isMobile is an array and not a boolean. Check the part where you define this variable. 

I'm no longer using this library because I moved to firebase and its authentication. Much easier, cleaner and safer!

**Comment by Abhijeetjaiswalit** [comment]
Thanks @TarikHuber  it looks like the error is coming from the library itself.Because i'm not defining any variable here. Thanks anyway..

**Comment by cristiano182** [comment]
Thaaanksss !!

**Comment by johnnywm** [comment]
I have spent 2 nights analyzing and trying to solve the bug, note that the redirect only happens, when the parent component is rendered from the client, if you refresh the page and load everything from the server, react-facebook-login works fine , the callback is executed. This behavior happens in mobile, in the Nextjs framework. The `disableMobileRedirect = {true}` works really well, @TarikHuber thank you very much, I was about to find another component and start everything from scratch
