### ISSUE TITLE
ReRequest  authentication

### ISSUE THREAD

**Issue by lineldcosta** [keppelen/react-facebook-login#126]
If i want to do auth_type: 'rerequest' to ask the user to grant more permission, how can i do it here?
I mean again when user clicks on "login to facebook" button instead of directly login to facebook it should popup, asking for permission. How can i achieve that with this plugin?

**Comment by keppelen** [comment]
@lineldcosta you can use `scope` - read more in doc https://github.com/keppelen/react-facebook-login#parameters

**Comment by advance512** [comment]
Let's say the user gave me permission to list only some of his Pages, but now he wants to add more. He then needs to rerequest, even though the scope permissions were granted - just not completely.

How can you do this?

**Comment by hamedazhar-giz** [comment]
@advance512 Did you get any solution?
