### ISSUE TITLE
2 issues in version 2.0.3

### ISSUE THREAD

**Issue by nguyenxuantruong** [keppelen/react-facebook-login#13]
-  Cannot read property 'parentNode' of undefined
- FB is not defined ( after start login )

**Comment by keppelen** [comment]
@nguyenxuantruong it ok to me.

![screenshot 2015-12-17 09 49 30](https://cloud.githubusercontent.com/assets/602111/11869056/83501d58-a4a3-11e5-9cb6-b54dc53e1929.png)

**Comment by nguyenxuantruong** [comment]
yes, Thanks @keppelen
