### ISSUE TITLE
Please correct!!!

### ISSUE THREAD

**Issue by dewid1985** [keppelen/react-facebook-login#131]
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

**Comment by kimcrab** [comment]
Same issue here.
Seems like latest version of react does not support propTypes via react package.

**Comment by andrewkamphuis** [comment]
I've added a pull request:  https://github.com/keppelen/react-facebook-login/pull/132 to resolve this issue.

**Comment by kimcrab** [comment]
@keppelen 
Hey, thanks for your quick response.
I just updated my package.json file but it's still 3.5.1 version.
How can I update to latest version which includes #132 merge?

**Comment by keppelen** [comment]
@kimcrab Hi, not yet, send new version tomorrow with new features
