### ISSUE TITLE
npm start giving error

### ISSUE THREAD

**Issue by hustlerism** [keppelen/react-facebook-login#133]
npm-debug.log

> 0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.15.9
3 info using node@v4.6.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart react-facebook-login@3.5.1
6 info start react-facebook-login@3.5.1
7 verbose unsafe-perm in lifecycle true
8 info react-facebook-login@3.5.1 Failed to exec start script
9 verbose stack Error: react-facebook-login@3.5.1 start: `NODE_ENV=development node_modules/.bin/webpack-dev-server --config webpack.config.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Users\hstlr\AppData\Roaming\nvm\v4.6.1\node_modules\npm\lib\utils\lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Users\hstlr\AppData\Roaming\nvm\v4.6.1\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:829:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid react-facebook-login@3.5.1
11 verbose cwd D:\Desktop\react-facebook-login
12 error Windows_NT 10.0.14393
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
14 error node v4.6.1
15 error npm  v2.15.9
16 error code ELIFECYCLE
17 error react-facebook-login@3.5.1 start: `NODE_ENV=development node_modules/.bin/webpack-dev-server --config webpack.config.js`
17 error Exit status 1
18 error Failed at the react-facebook-login@3.5.1 start script 'NODE_ENV=development node_modules/.bin/webpack-dev-server --config webpack.config.js'.
18 error This is most likely a problem with the react-facebook-login package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     NODE_ENV=development node_modules/.bin/webpack-dev-server --config webpack.config.js
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs react-facebook-login
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls react-facebook-login
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by keppelen** [comment]
@hustlerism i tested it on mac os and everything worked fine. I used npm and yarn for testing
