### ISSUE TITLE
Warning: Failed prop type: Calling PropTypes validators directly is not supported by the `prop-types` package. Use PropTypes.checkPropTypes() to call them. Read more at http://fb.me/use-check-prop-types

### ISSUE THREAD

**Issue by septembermd** [keppelen/react-facebook-login#135]
Warning: Failed prop type: Calling PropTypes validators directly is not supported by the `prop-types` package. Use PropTypes.checkPropTypes() to call them. Read more at http://fb.me/use-check-prop-types

**Comment by arfianadam** [comment]
I'm getting this too.

**Comment by huynguyenh** [comment]
because PropTypes in React has been deprecated in 15.5, you have to install prop-types package to replace it

**Comment by septembermd** [comment]
@huynguyenh thank you cap, we did it already

**Comment by arfianadam** [comment]
Yep, already using `prop-types`

**Comment by arfianadam** [comment]
Reverting to `React`'s own `PropTypes` prevents this error. I checked the code and there is no PropTypes function used but somehow this shows up. Gonna recheck.

**Comment by andrewkamphuis** [comment]
@arfianadam React's own PropTypes are depreciated in React 15.5.   This isn't throwing any errors /warnings for me (I wrote the pull request for converting to prop-types).  I'll play around with this further today.

**Comment by andrewkamphuis** [comment]
@septembermd what version of React are you using?

**Comment by septembermd** [comment]
@andrewkamphuis 15.5.4

**Comment by andrewkamphuis** [comment]
@septembermd can you send me your package.json file.  I'm having trouble duplicating this (and I feel a bit responsible because it was my pull request).

**Comment by septembermd** [comment]
`{
  "name": "bus",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "konva": "^1.6.0",
    "prop-types": "^15.5.4",
    "react": "^15.4.2",
    "react-dom": "^15.4.2",
    "react-facebook-login": "^3.5.0",
    "react-konva": "^1.1.1",
    "react-modal": "^1.7.3",
    "react-redux": "^5.0.3",
    "react-router-dom": "^4.1.1",
    "redux": "^3.6.0",
    "redux-thunk": "^2.2.0"
  },
  "devDependencies": {
    "cross-env": "^4.0.0",
    "eslint": "^3.19.0",
    "eslint-config-airbnb": "^14.1.0",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-react": "^6.10.3",
    "react-scripts": "0.9.5"
  },
  "scripts": {
    "start": "cross-env NODE_PATH=src/ react-scripts start",
    "build": "cross-env NODE_PATH=src/ react-scripts build",
    "test": "cross-env NODE_PATH=src/ react-scripts test --env=jsdom",
    "eject": "cross-env NODE_PATH=src/ react-scripts eject"
  },
  "eslintConfig": {
    "extends": "airbnb",
    "installedESLint": true,
    "parser": "babel-eslint",
    "parserOptions": {
      "ecmaFeatures": {
        "jsx": true,
        "modules": true
      }
    },
    "plugins": [
      "react",
      "jsx-a11y",
      "import"
    ],
    "globals": {
      "window": true,
      "document": true,
      "navigator": true
    },
    "rules": {
      "import/no-named-default": 0,
      "react/jsx-tag-spacing": 0,
      "react/no-array-index-key": 0,
      "react/require-default-props": 0,
      "react/jsx-filename-extension": [
        1,
        {
          "extensions": [
            ".js",
            ".jsx"
          ]
        }
      ],
      "react/forbid-prop-types": 0,
      "import/extensions": 0,
      "import/no-extraneous-dependencies": [
        0
      ],
      "import/no-unresolved": 0,
      "max-len": [
        2,
        160,
        2
      ]
    }
  }
}
`

**Comment by andrewkamphuis** [comment]
@septembermd I'm unable to duplicate - are you sure its in the this component?  There are no validators being called directly on any of the PropTypes.

**Comment by spiderhc** [comment]
@andrewkamphuis I'm with the same problem, and I'm sure the problem is being from this component. 
-**React Version**: 15.0.0
PS: I had installed **prop-types** for unsuccessful testing.

Code from my component:

```import React, { Component } from 'react';
import FacebookLogin from 'react-facebook-login';

class FacebookLoginComponent extends Component {
  render() {
    return (
      <FacebookLogin appId="myAppID" version="2.9" xfbml="1" />
    )
  }
}
export default FacebookLoginComponent;```

**Comment by arfianadam** [comment]
@andrewkamphuis I tried removing the component and all was fine. I did a bit of research too and took a look at the code. You're right, nothing's wrong. There's no validators called directly. I have no idea why this happen.

**Comment by andrewkamphuis** [comment]
@arfianadam - thanks.  It's happening in the bundling of the distribution files.  If you clone the repository and run it directly from source it's fine.  We might need @keppelen assistance.

**Comment by septembermd** [comment]
@andrewkamphuis i found out that source was not correctly built.

**Comment by andrewkamphuis** [comment]
@keppelen - if we change the compiling of the bundle to use the babel-cli rather than using webpack to bundle the distribution - this issue goes away.  I'll make another pull request.

**Comment by arfianadam** [comment]
@andrewkamphuis what's wrong with using webpack?

@septembermd I already cloned the repo and run the `bundle` command, manually replacing the one in my project's `node_modules` with the one I just bundled and the warning didn't go away.

**Comment by arfianadam** [comment]
well, I tried removing these lines:
```javascript
new webpack.DefinePlugin({
  'process.env':{
    'NODE_ENV': JSON.stringify('production'),
  },
}),
```
and it suddenly works. Is it necessary to bundle the `react` lib in production state?

**Comment by keppelen** [comment]
https://github.com/keppelen/react-facebook-login/commit/2c5b22b82b1f27456348cf38f617091787769fb1

**Comment by arfianadam** [comment]
Well, for me this still persists 😁 gonna re-check

**Comment by septembermd** [comment]
@keppelen @arfianadam @andrewkamphuis for me issue still persists as well , using create-react-app (mb this info will help)

**Comment by whnunlife** [comment]
Using latest react-boilerplate and getting the above error as well.

**Comment by mbeauchamp7** [comment]
Just installed 3.6.0 and it's still there

**Comment by kimcrab** [comment]
Me as well. I still have this error.
react-facebook-login v3.6.0
react v15.5.4
