### ISSUE TITLE
SecurityError

### ISSUE THREAD

**Issue by maxsalven** [keppelen/react-facebook-login#139]
Unfortunately I can't find an easy way to reproduce this.  However I frequently get error reports from Sentry with a SecurityError. `react-facebook-login` is the only component in my app that talks to Facebook, so I assume the error is related somehow to this package.

**Blocked a frame with origin "https://www.(mydomain).com" from accessing a frame with origin "https://staticxx.facebook.com". The frame being accessed set "document.domain" to "facebook.com", but the frame requesting access did not. Both must set "document.domain" to the same value to allow access.**

Has anyone else encountered this problem? Thanks.

**Comment by tstirrat15** [comment]
Yep, also seeing this issue. I don't know what it's related to, though.

**Comment by 6192dp** [comment]
Seeing the same issue on Sentry reports. Not sure how to reproduce though. Any leads?

**Comment by tstirrat15** [comment]
@keppelen what was your reason for closing this? If it's a wontfix for one reason or another, it'd be helpful to us to know why.
