### ISSUE TITLE
changing styles

### ISSUE THREAD

**Issue by foodaka** [keppelen/react-facebook-login#14]
Hi, im trying to change the color and size of the button. When i change these styles in the facebook.scss file, it does not change. for example, if i change to yellow the button stays blue. tks

$font-family-default: 'Helvetica', sans-serif;

@function calc-responsive($value1, $width1, $value2, $width2) {
  $x1: $width1;
  $x2: $width2;
  $y1: $value1;
  $y2: $value2;
  $a: ($y2 - $y1) / ($x2 - $x1);
  $b: ($x2 * $y1 - $x1 * $y2) / ($x2 - $x1);
  @return calc(#{$a*100vw} + #{$b*1px});
}

%button {
  font-family: $font-family-default;
  font-weight: bold;
  -webkit-font-smoothing: antialiased;
  border-width: 2px;
  border-style: solid;
  color: #FFF;
  cursor: pointer;
  display: inline-block;
  font-size: calc-responsive(12, 768, 18, 1920);
  text-decoration: none;
  text-transform: uppercase;
  transition: background-color .3s, border-color .3s;
  background-color: yellow;
  border-color: yellow;
}

.small {
  @extend %button;
  padding: 1.2em 3em;

  @media (min-width: 768px) {
    padding: 0.9em 2.2em;
  }
}

.medium {
  @extend %button;
  padding: 1.2em 3em;

  @media (min-width: 768px) {
    padding: 1.6em 2.4em;
  }
}

.metro {
  @extend %button;
  border-radius: 0;
}

**Comment by moidmw** [comment]
There are two ways to change style.. either build from source by re-building from source code or edit styles in facebook-login.js file in dist folder.

**Comment by keppelen** [comment]
Hi @foodaka I recommend something like that

Your style, in your project
```css
.kep-login-facebook {
    background: yellow;
}

.kep-login-facebook.kep-login-facebook-small {
   padding: 5px 10px
}
```

**Comment by foodaka** [comment]
hey keppelen your solution did not work, moidmw was correct, i needed to modify the facebook-login.js file in the dist folder. thanks for the replies!
