### ISSUE TITLE
Problem with mobile login

### ISSUE THREAD

**Issue by joelcalheiros** [keppelen/react-facebook-login#140]
Hello, there is a problem with the login on the mobile phone.
Here is mu code:
<FacebookLogin
appId={MyFBAppId}
autoLoad={false}
textButton="Login Facebook"
cssClass="btn btn-facebook"
fields="name,email,picture"
scope="user_birthday,user_likes,user_location,email,user_friends"
isMobile={true}
disableMobileRedirect={true}
callback={this.responseFacebook}
/>

What could be wrong?

Thanks

**Comment by keppelen** [comment]
@joelcalheiros what error message are you receiving?

**Comment by joelcalheiros** [comment]
After the facebook page closes nothing happend.

**Comment by keppelen** [comment]
you have a log or image this case?

**Comment by joelcalheiros** [comment]
Hi, I change to other component and the problem is the same, probably is in the REST API

Thanks
