### ISSUE TITLE
Status unknown on mobile iOS safari

### ISSUE THREAD

**Issue by antonellil** [keppelen/react-facebook-login#143]
Hello,

I believe I have narrowed the issue down to this line:
https://github.com/keppelen/react-facebook-login/blob/master/src/facebook.js#L162

And I have inspected my site which is running on mobile safari on iOS 10 (most recent). The status is for some reason coming back as unknown, and then it hits the else statement for that line of code, and the FB.login does not do anything at all.

I think the solution is to do that oauth alternative link as is done on click. Does that sound reasonable? I will try to fix it and submit a PR.

EDIT: After digging a little more I am not entirely sure why the response status is unknown. Any ideas?

EDIT2: 3rd party cookies are not disabled. I am able to login properly on Safari private browsing.

**Comment by sibelius** [comment]
@antonellil have you fixed this?
