### ISSUE TITLE
How to get user's friend list

### ISSUE THREAD

**Issue by Abhijeetjaiswalit** [keppelen/react-facebook-login#148]
Even after setting scope = 'user_friends', I'm not getting friend list in response. For test purpose I've also allow the same permission for the same application in my friend's account.

**Comment by minhbk** [comment]
I have the same problem.

**Comment by kkseven07** [comment]
any solutions?

**Comment by Abhijeetjaiswalit** [comment]
Yes. Try this. This should work 👍 

<FacebookLogin
                              appId="your_appid"
                              cookie={true}
                              xfbml={true}
                              version='2.8'
                              autoLoad={false}
                              fields="name,email,friends,picture"
                              scope="public_profile,email,user_friends"
                              callback={this.responseFacebook.bind(this)}
                              disableMobileRedirect={true}
                              cssClass='loginBtn loginBtn--facebook'
                              textButton={locale.signin.facebook}
                            />

**Comment by pokhrelashok** [comment]
Can anyone tell me how to get the scopes? I dont get the data back with the response
