### ISSUE TITLE
Feature request - allow auth_type: rerequest

### ISSUE THREAD

**Issue by aryehrein** [keppelen/react-facebook-login#149]
if you'll add 
` if (reRequest) {
        params.auth_type = 'rerequest';
      }`

it will allow facebook to ask for missing permissions.

In the react component:

Thanks for great module 
`
                        <FacebookLogin
                            reRequest={true}`

Much like reAuthenticate prop

**Comment by advance512** [comment]
Any update on this?

**Comment by jakewilson801** [comment]
I also need this or a way to supply params to the request(which might make the lib more flexible).

**Comment by advance512** [comment]
Update? :)

**Comment by jakewilson801** [comment]
I ended up forking the repo and just intergrating it into my project.
