### ISSUE TITLE
Scope seems to have no effect when used via click event

### ISSUE THREAD

**Issue by joewood** [keppelen/react-facebook-login#15]
The `scope` data isn't returned from `/me` when called after login via the click handler (explicit `FB.login`).
I've changed the code to explicitly ask for the scope fields and this seems to work. e.g.
```javascript
FB.api("/me?fields=id,first_name,last_name,link,gender,locale,timezone,email", ....)
```

Not sure if this is a version API issue, or an app config problem. I seem to remember it used to work.

**Comment by moidmw** [comment]
I tried including scope but it didnt work. The only data I got was name, appId and accesstoken..
What can I do get complete data (social_data and email)?

**Comment by DevAlien** [comment]
I made a pull request to solve this issue: https://github.com/keppelen/react-facebook-login/pull/18 let's home @keppelen merges it as soon as possible if not I will push a fork on npm for the moment

**Comment by keppelen** [comment]
Thank you @DevAlien :)

**Comment by DevAlien** [comment]
@keppelen Have you published the new version on npm?

**Comment by keppelen** [comment]
@DevAlien https://www.npmjs.com/package/react-facebook-login :smile:
