### ISSUE TITLE
can't setState

### ISSUE THREAD

**Issue by Dave-Algorism** [keppelen/react-facebook-login#150]
Hello, I want to grab data and set them to the fields using this.setState in responseFacebook(response) method but I get  " Uncaught TypeError: this.setState is not a function". Please, help me out.

Secondly, how do I redirect to a different route/page when the facebook button is clicked? I am trying to implement this in react

**Comment by stvmachine** [comment]
+1

**Comment by konutis** [comment]
Bind 'responseFacebook' function to this in constructor.
constructor(props) {
    super(props);
    this.responseFacebook = this.responseFacebook.bind(this);
}
