### ISSUE TITLE
open in new window

### ISSUE THREAD

**Issue by palakt4f** [keppelen/react-facebook-login#151]
Hello, I want open facebook login with new tab. Please, help me out.
So, It will not reload my app. (It's better for my app performance)

I just want functionality as react-google-login

**Comment by sumit-gupta91** [comment]
I also want the same functionality, why has this issue been closed ?

**Comment by Zhastreaus** [comment]
+1

**Comment by simonsiu2017** [comment]
try isMobile={false}
