### ISSUE TITLE
change "Login with facebook" text

### ISSUE THREAD

**Issue by arpecop** [keppelen/react-facebook-login#153]
Excuse me if it is already possible , I wan to change the text on the button for non english speakers audience

**Comment by rcallaghan** [comment]
It is possible, you pass through the text you want as textButton eg
`  <FacebookLogin
    textButton="Sign up with Facebook"
    appId="1088597931155576"
    autoLoad={true}
    fields="name,email,picture"
    onClick={componentClicked}
    callback={responseFacebook} />`

**Comment by satyanash** [comment]
I think this issue can be closed now.
