### ISSUE TITLE
Add option to use FontAwesome icons without adding a link element

### ISSUE THREAD

**Issue by advance512** [keppelen/react-facebook-login#154]
If, in my app, I already have the FontAwesome fonts bundled, I'd like not to redownload the fonts again.

Perhaps a prop - `disableFontAwesomeLink`?

**Comment by makemek** [comment]
You can pass a react component to `icon` prop
In this case
```
<FacebookLogin
  appId="xxxxxx"
  icon={<i className="fa fa-facebook"></i>}
/>
```
It will use that component and doesn't render `<link>` tag

**Comment by keppelen** [comment]
Thanks @makemek
