### ISSUE TITLE
I have to make my customized Button so how can I use it <FacebookLogin> and Login page popup on page load I want that it should on button click

### ISSUE THREAD

**Issue by chandan7193** [keppelen/react-facebook-login#156]
`import React, { Component } from 'react';
import { Grid, Button } from 'semantic-ui-react';
import FacebookLogin from 'react-facebook-login';

import './SignUp.css';

class SignUp extends Component{

 

	responseFacebook(response) {
      	console.log(response);

    }
   
 

      render(){
      	return(
      		<div className="message">
      		<Grid divided="vertically" columns="equal">

      		<Grid.Row>
      		<Grid.Column>
      		<div className="UserDetails">

      		<FacebookLogin
	          appId="xxxx"
	          autoLoad={true}
	          fields="name,email,picture"     
    		    
	          scope="xxx,xxx"
	          callback={this.responseFacebook}
           
            cssClass="my-facebook-button-class" 
            size="medium" 
	        />

      		</div>
      		<div className="display" id="display">

      		</div>

      		</Grid.Column>
      		</Grid.Row>

      		</Grid>
      		</div>

      		);
      	}
      }

      export default SignUp;`

**Comment by Matus-Stastny** [comment]
You should set autoLoad to false, or remove it (default value is false).
