### ISSUE TITLE
Blank popup when revisiting page that has the button

### ISSUE THREAD

**Issue by zebapy** [keppelen/react-facebook-login#16]
The button works fine when you first load the page and log in with it. The issue is when you visit a react page that has the button, go to another page, then revisit that page with the button, I'm getting the popup for the facebook auth but it is blank and just hangs. Is this an issue with my Facebook app settings or this module?

**Comment by zebapy** [comment]
Needed to have `fb-root` element near the `body` tag else it got cleared out on page change.

**Comment by joshgeller** [comment]
Thank you @zebapy that was driving me absolutely insane.

**Comment by zebapy** [comment]
@keppelen think this would be worth fixing?

**Comment by keppelen** [comment]
@zebapy you can record your screen? I not understand your question.

**Comment by zebapy** [comment]
@keppelen it's a problem with this module if the user wants the button on multiple pages using react router. I think this should change so `fb-root` is appended to the body, and not next to the button. 

I'll try to create a gif/screencast or repro steps soon

**Comment by keppelen** [comment]
@zebapy  @joshgeller https://github.com/keppelen/react-facebook-login/commit/b7ae1ab0055a217192cff9cf73c1cf192da5bd2f :smile:
