### ISSUE TITLE
Have you tried to login through facebook app internal browser?

### ISSUE THREAD

**Issue by kimcrab** [keppelen/react-facebook-login#161]
I'm using iPhone 6s and have launched my app using react-facebook-login.

It's working all well except one case. When you tried to login through facebook/instagram app internal browser with iPhone, It never redirects back to my website.

I thought I was about domain problem, but it's working OK with Android phone.

-If you want to see this bug on instagram app 
1. Turn on instagram app with your **iPhone** 
2. Search **tteonago** on the search bar
3. Click tteonago user and go to it's website(www.tteonago.com)
4. Open the tab on the left top and click 로그인(login)
5. The blue button is react-facebook-login(페이스북으로 시작하기).

-If you want to see this bug on facebook app
1. Turn on facebook app with your **iPhone** 
2. Search **tteonago** on the search bar
3. Click 떠나Go page and go to it's website(www.tteonago.com)
4. Open the tab on the left top and click 로그인(login)
5. The blue button is react-facebook-login(페이스북으로 시작하기).

This is pretty big problem for me because I'm using instagram/facebook as a marketing channel.
Please check this bug. Thanks in advance.

**Comment by samuxyz** [comment]
@kimcrab have you tried to check this issue [175](https://github.com/keppelen/react-facebook-login/issues/175) ?
It might solve your problem.

**Comment by victorcfernandes** [comment]
I'm currently having the same issue on my app. Setting `disableMobileRedirect` did not work...

**Comment by nicoqh** [comment]
Setting `disableMobileRedirect` has the opposite effect; you want to *enable* the redirect flow.

Using the in-app browser, your app and the popup window can't communicate. This leads to the error you describe.

You should use the redirect flow instead, which this library tries to trigger when the user is on a mobile device. However, if the `getIsMobile()` check doesn't work in your case (i.e. doesn't return `true` while using the internal Facebook browser), you can force all logins to use the redirect flow by setting the `isMobile` prop to `true`. And don't pass the `disableMobileRedirect` prop.

**Comment by sibelius** [comment]
any solution to this?

**Comment by alen12345** [comment]
We are experiencing the same issue currently.

**Comment by Samuel-Celko** [comment]
Currently experiencing the same issue, login working on everything but in app browsers (Instagram, Facebook) where the window redirects and therefore loses all the necessary handlers

**Comment by TharakaSl** [comment]
@Samuel-Celko Did you find a issue for login not working in in app browsers? ( Facebook )

**Comment by sidharrth2002** [comment]
Hi, is there currently a solution for in-app browser logins?
