### ISSUE TITLE
Picture response

### ISSUE THREAD

**Issue by redhmam** [keppelen/react-facebook-login#163]
The answer brings me an image with size 50x50. How to get bigger sizes?

**Comment by AlexanderCollins** [comment]
@redhmam Here is an example, I took this from the Facebook Javascript API. Check out the 'parameters' section: https://developers.facebook.com/docs/graph-api/reference/user/picture/

`  
<FacebookLogin
        ...
        fields="id,name,picture.width(100)"
        ...
        />
`

You can also set height simultaneously; `picture.width(x).height(y)`. Facebook will crop the larger quantity from the photo (this is however, not documented).

**Comment by redhmam** [comment]
Thanks! @AlexanderCollins

**Comment by alexgvozden** [comment]
thanks @AlexanderCollins  for the answer
