### ISSUE TITLE
getting console error Cannot read property 'logPageView' of undefined

### ISSUE THREAD

**Issue by Abhijeetjaiswalit** [keppelen/react-facebook-login#164]
@keppelen Don't know what happened, It was working fine but when I reload the page I get - Cannot read property 'logPageView' of undefined. again refresh, the error was gone. again refresh, error appears.

**Comment by stkrzysiak** [comment]
FWIW I'm seeing this in a non-react project. I didn't work on this code until now but if I had to guess the  fb js client wasn't configured properly.
