### ISSUE TITLE
[Featured Request] Custom button component

### ISSUE THREAD

**Issue by stefensuhat** [keppelen/react-facebook-login#168]
Instead of custom css class, It will be great if you can make custom component  for the button. 

For example if I want to use material-ui button I can extend it easily.

**Comment by sbalazote** [comment]
That would be great, I was wondering if there is a trick to use a FlatButton or RaisedButton from material-ui ?

**Comment by advance512** [comment]
I agree. I need this too.

Look at the style of custom render done in filestack-react:
https://github.com/filestack/filestack-react

```
<ReactFilestack
  apikey={apikey}
  options={options}
  onSuccess={onSuccess}
  onError={onError}
  render={({ onPick }) => (
    <div>
      <strong>Find an avatar</strong>
      <button onClick={onPick}>Pick</button>
    </div>
  )}
/>
```

Awesome and to the point.

Need a PR or can you take it into your roadmap?

**Comment by keppelen** [comment]
@advance512 pleas, try this
```jsx
<ReactFilestack
  apikey={apikey}
  options={options}
  onSuccess={onSuccess}
  onError={onError}
  render={({ onPick }) => (
    <FacebookLogin
        appId=""
        autoLoad={true}
        fields="name,email,picture"
        onClick={componentClicked}
        callback={responseFacebook} />
  )}
/>
```

**Comment by advance512** [comment]
Hey @keppelen ,

Thanks for the response. Not sure I was clear in what I requested.

The point I was making is: I don't want the standard rendering by the FacebookLogin class. None of it.
It does not matter how I change the class or styles, it still does not look like the Material UI components I use, or at the very least - doubles the locations where I have to change styling, etc.

I want to have the FacebookLogin class create the LOGICAL implementation, and the VISUAL one be done by a render(onClick) method that I offer the FacebookLogin class, which let's me create my own UI component and simply connect connect its own click/touch/whatever event to the onClick method received as an argument. This onClick method will be implemented by FacebookLogin, and do the entire FB flow as required, and will also eventually called the callback, etc.

Hope I was more articulate this time around. :)

**Comment by samuxyz** [comment]
@keppelen @advance512 guys I can help as well, in case, as I am one of the owners of [filestack-react](https://github.com/filestack/filestack-react).

**Comment by advance512** [comment]
@keppelen what do you think?

**Comment by vigneshprasad** [comment]
```React
<FacebookLogin
    callback={this.responseFacebook}
    cssClass="facebook-button"
    textButton=""
    icon={<img alt={"Facebook"} src={facebookButton} />} />
```
This is what I used to solve this problem. You can put whatever button component you want in the icon prop. I removed the border and background of the default button using css for the 'facebook-button' class. In addition to this I made sure the textButton prop is empty. Otherwise the "Login through facebook" text will show up regardless.

**Comment by shilangyu** [comment]
@vigneshprasad  your solution works however putting a button in `icon` throws a warning of: 'validateDOMNesting(...): <button> cannot appear as a descendant of <button>'.

```ts
<FacebookLogin
	appId="1234"
	fields="name,email,picture"
	buttonStyle={{ all: 'unset' }}
	callback={callbackFunc}
	textButton=""
	icon={<Button flavor="facebook">Continue with Facebook</Button>}
/>
```
