### ISSUE TITLE
Login without a popup

### ISSUE THREAD

**Issue by karanthakral** [keppelen/react-facebook-login#173]
How to login without a popup in the same browser window and not with the popup(The popup is usually blocked by chrome? The same option is available as uxMode in react-google-login.

**Comment by karanthakral** [comment]
@keppelen any updates?

**Comment by maml** [comment]
Try setting `isMobile={true}`, that worked for me.

Note that depending on a user's security settings, like if they have 2FA turned on, they will be prompted to re-enter their password even if logged in, when landing on your app's approval page from a redirect. This wouldn't be the case with the pop up. With 2FA turned on if you hit the pop up and you're already logged in, you're not asked to re-enter your password. Just something to think about. For me it's worth it though, anything to avoid pop-ups.

**Comment by ticruz38** [comment]
The problem mis exactly the reverse to me, I wish I have a popup but always get a redirect.
