### ISSUE TITLE
prop `disableMobileRedirect` is undocumented

### ISSUE THREAD

**Issue by satyanash** [keppelen/react-facebook-login#175]
The `disableMobileRedirect` prop is not documented in the README and the behaviour where the component uses a popup to authenticate from Facebook does not carry forward to mobile devices where instead it prefers the redirection method.
This should be documented.

**Comment by bitstrider** [comment]
What should we set the `disableMobileRedirect` value to if we want to keep using popup for mobile devices?

**Comment by JUnderwood1991** [comment]
Thank you for posting this issue, I couldn't figure out for the life of me why people visiting the webpage from a mobile browser weren't able to login. Setting the prop to true worked. You're right this should be documented.

**Comment by satyanash** [comment]
> So should we set the disableMobileRedirect prop to true if we want to keep using popup for mobile devices.

Yes, that way it works similar to as it would on a desktop.

**Comment by bitstrider** [comment]
To be sure, I'm currently using popup for mobile with no issues. Even works for FB browser

**Comment by steveliles** [comment]
Facebook login on mobile stopped working for us some time last week, with no changes at our end - I'm assuming facebook changed something. 

Anyhoo, `disableMobileRedirect={true}` has done the trick, but I only found out about it because I stumbled on this issue.

**Comment by sibelius** [comment]
disableMobileRedirect={true}

solves the problems for us
