### ISSUE TITLE
componentClicked undefined in readme

### ISSUE THREAD

**Issue by antoinecollas** [keppelen/react-facebook-login#181]
`componentClicked` is used in the first example of README but not defined

**Comment by puffstream** [comment]
Same

**Comment by jmpsimoes** [comment]
Have you solved the problem guys? i have the same problem.

**Comment by jyoonsong** [comment]
You should declare the variable `const componentClicked` first. That will solve the problem.
If you do not need the variable, you can simply delete the parameter `onclick={componentClicked}`.
