### ISSUE TITLE
Can you add "component" prop to provide custom button?

### ISSUE THREAD

**Issue by serhiipalash** [keppelen/react-facebook-login#182]
Hi!
You have a great library!
Can you add "component" prop to pass custom button component into it? Often customizing only with className is not enough.

**Comment by mlajtos** [comment]
This is a really good proposal. Now, there are several props that deal just with the appearance of the login button (namely: `size`, `textButton`, `typeButton`, `cssClass`, `icon`, `tag`, `containerStyle`) and still there are use cases that can't be covered. An ability to use own visual component would definitely help.

My proposal is to provide a render prop:
```
<FacebookLogin
    appId="..."
    fields="..."
    callback={...}
    render={(props) => {
        const { isDisabled } = props // loading SDK failed (or some other reason)
        <button className="fb-login-button" disabled={isDisabled}>Login</button>
    }}
/>
```

**Comment by XPLOT1ON** [comment]
was about to post about this proposal too. passing in custom component would be good.

**Comment by jackfranklin** [comment]
Version 4 has this as per my PR : #196

**Comment by shilangyu** [comment]
Why is `render` in a different import? Cant it be just in the default import or as a named import from 'react-facebook-login'?
