### ISSUE TITLE
How to logout?

### ISSUE THREAD

**Issue by jamland** [keppelen/react-facebook-login#190]
Sorry if this is silly question but how actually to do logout with this component?

**Comment by francisrod01** [comment]
I've asked the same question.

**Comment by jamland** [comment]
oh.. haven't seen it @francisrod01 
Anyway, I have ended implementing FB auth myself without packages. 
That actually took less time than looking/trying for something suitable 😁

**Comment by francisrod01** [comment]
oh, It's good, @jamland !
I'm just use a local store session and `autoLoad={false}`

**Comment by jamland** [comment]
got your trick =)
isn't this way user stay logged until she refresh the page?

**Comment by francisrod01** [comment]
If you save in local store no, because it was saved in your browser store until you clean browser data.
I also saved the user in the first succeed authentication.
