### ISSUE TITLE
continue as {username}

### ISSUE THREAD

**Issue by kherrohan** [keppelen/react-facebook-login#191]
How can i show continue as {username}, like on pinterest? Is there any parameter to add in the code?

**Comment by kherrohan** [comment]
expecting some information on this.

**Comment by chanthafef** [comment]
You can easily update the message within the button with the textButton props. So maybe just save username to localStorage (after first login) and display your custom message using the textButton props

**Comment by theGABS** [comment]
@chanthafef no, continue as {username} show correct username even before user login on you site.

**Comment by kherrohan** [comment]
the parameters that are mentioned in the plugin doesnt have an option for "continue as {username}" please let me know if i am wrong somewhere and through which parameter i can have this functionality.

ref: https://github.com/keppelen/react-facebook-login

**Comment by bytheway875** [comment]
^^ I'm pretty sure that you can set "autoLoad" to true, which will load the facebook data you've requested as soon as the page loads (as long as they've authorized your app, I think.)

However, I don't think there is a "username" as such for Facebook. I think that if you are a developer, you use your custom path as a username (so for men, facebook.com/shannonleighbyrne), but most users probably don't really identify with that as their Facebook "username".

Also, with all of the privacy issues with Facebook in the news recently, you might not want to take data that you collect and show it to them on the page without an explicit opt-in from the user, but that's just my editorialized UX opinion.

**Comment by iyobo** [comment]
@bytheway875 I think that should be up to the individual developers to decide, not the library. 

To enable the requested feature, it is as easy as allowing users set `data-use-continue-as="true"`.

**Comment by iyobo** [comment]
See for details https://developers.facebook.com/docs/facebook-login/web/login-button/
