### ISSUE TITLE
Empty Facebook popup after login

### ISSUE THREAD

**Issue by h476564406** [keppelen/react-facebook-login#203]
This is my code. The effect I want is no popup, just redirect.
![image](https://user-images.githubusercontent.com/19324642/35569349-f18686b0-0606-11e8-9c0d-df6bdfaae521.png)
Fackbook login first time is normal, but when I logout, then login again, there has a Empty Facebook popup(the browse I test are google chrome and firefox). How can I fix this? Any idea is appreciated!
![image](https://user-images.githubusercontent.com/19324642/35569575-62120c38-0607-11e8-8675-3d85877d5b9c.png)
My logout code:
window.FB.logout()

**Comment by vitalyliber** [comment]
@h476564406 in my case I have the same issue when component with facebook button initialize the second time.
I tried to login only via facebook SDK and this worked perfectly. I don't know why..

**Comment by vitalyliber** [comment]
I use only one component with facebook auth in my server rendering app. My app has the framework 'turbolinks' for fast reloading pages. It is default in Ruby on Rails. I think an issue related with it. 
I solved my problem. After visit login page I remove FB global variable and reload fb SDK. It look like strange way, but it works for me.

**Comment by h476564406** [comment]
@vitalyliber Thank you!

**Comment by MAkif06** [comment]
Hi everyone, I am developing a maven project. Thanks to my Facebook develop application, I am trying to share something from my maven project on my page. Before sharing something on my page, I need to log in to my account. I have not any problem about log in, I have a problem after the log in. That is, after log in process facebook open a blank modal as you seen in picture:

![image](https://github.com/keppelen/react-facebook-login/assets/96817707/6ff5ee61-6064-4bc3-a79f-9fa23f45b0a9)

When i look at the console in chrome index facebook throw this exception:

![image](https://github.com/keppelen/react-facebook-login/assets/96817707/433993d5-9f61-4831-98d7-814d37527535)

I did not find any solition about this exception and i did not understand why am i gettin this error ? Thanks for your helps.

**Comment by h476564406** [comment]
已经收到。

**Comment by MAkif06** [comment]
> 已经收到。

Did you solve this problem ?
