### ISSUE TITLE
Email Permissions

### ISSUE THREAD

**Issue by zanisis** [keppelen/react-facebook-login#208]
How to handle if user unchecklist email on user permissions. because i need email from facebook. right now data from your callback is email user not permission / email not set public i want to do something.

**Comment by kaizenberg** [comment]
@zanisis with some Facebook accounts, the **email field is not present** in the response after click Facebook login. And with others accounts the email field **is present...**

Is your same problem?

**Comment by nicoqh** [comment]
Some Facebook users decide not to share their email address, and some users don't have an email attached to their Facebook account at all (e.g. they signed up with their phone number).

You app needs to handle this case, either by asking your users to provide an email before the registration can be completed, or by allowing registrations without email.

**Comment by morrigan** [comment]
This is a valid question. I suppose you should use Facebook logout in your app so the user can login again with the email permission. However, it seems that I cannot make that logout.

**Comment by shyela** [comment]
IIRC, you can use `FacebookLogin` with a `scope` property with all the permissions you want, even if the current user has already auth'd your app and there is already a valid auth session. Specifically, if you present a `FacebookLogin` component with different permissions than are currently granted, when it is clicked on (or if `autoload` is `true`) it will cause a FB permission popup window to launch, asking for the un-granted permissions.
