### ISSUE TITLE
Fb login doesn`t work on Firefox private window when Firefox Tracking Protection is ON

### ISSUE THREAD

**Issue by Zyphroid** [keppelen/react-facebook-login#209]
The poop-up doesn`t get triggered when trying to use the facebook login. This only happens on Firefox private window and only when the Tracking Protection is on. (it works on Chrome incognito)

 The error I get is 
TypeError: window.FB is undefined

 Some people say it s the security policy at Firefox for client side:
https://stackoverflow.com/questions/33855626/firefox-blocking-facebook-js

 Maybe this gives someone a better hint:
https://stackoverflow.com/questions/40466492/how-to-fix-error-fb-is-not-defined-no-undef-on-create-react-app-project

**Comment by nickgermaine** [comment]
I had a similar problem using the firefox extension Disconnect, which prevents tracking scripts from running.  Facebook sdk won't run under those conditions, and it's a problem between facebook and firefox.  There is nothing that anybody can do about it here.

**Comment by sibelius** [comment]
how can we prevent this?

**Comment by keppelen** [comment]
@Zyphroid  you can send a PR with this solution?

**Comment by AlexAvlonitis** [comment]
Mozilla is looking at it as well: https://bugzilla.mozilla.org/show_bug.cgi?id=1226498
It breaks many sites not just fb.
