### ISSUE TITLE
Login with facebook not working with Mobile Browser

### ISSUE THREAD

**Issue by lokeshbansal1993** [keppelen/react-facebook-login#210]
Hello Plugin Developer,

Thanks for help for using this plugin.

I'm using your plugin but I faced the problem when our website open in mobile browser then login with facebook not working properly.

Website: http://www.atayata.com/

Please help me and give me some suggestion to fix the problem.

Thanks

**Comment by treant-prime** [comment]
I think this issue will resolve it https://github.com/keppelen/react-facebook-login/issues/146

**Comment by lokeshbansal1993** [comment]
Thanks..resolved this issue
