### ISSUE TITLE
undefined is not an object (evaluating 'window.FB.login')

### ISSUE THREAD

**Issue by adrienharnay** [keppelen/react-facebook-login#214]
Hey,

I have a lot of reports on Sentry about an error: `undefined is not an object (evaluating 'window.FB.login')`, which happens when using uBlock for example.

Here is the snippet: ```//www.facebook.com/dialog/oauth"+(0,p.default)(u):window.FB.login(n.checkLoginState,{scope:o,return_scopes:a,auth_type:u.auth_type})}}},i=o,```

I think we could `try {} catch {}` around the call, or ensure `window.FB` exists before performing it. If it fails, then calling onError would be a great way to allow the user to handle the failure.

I can submit a PR if you want, just tell me if I need some context to work on it.

Thanks!

**Comment by sibelius** [comment]
how can we prevent this?

**Comment by keppelen** [comment]
@adrienharnay you can send a PR with this solution?

**Comment by rmoedt** [comment]
Created a PR with a fix for this: https://github.com/keppelen/react-facebook-login/pull/242

**Comment by adrienharnay** [comment]
Wow, sorry I somehow missed the notifications. Thanks a lot for the fix!
