### ISSUE TITLE
not working on browser on mobile

### ISSUE THREAD

**Issue by zanisis** [keppelen/react-facebook-login#215]
i try login facebook web on mobile, i using Safari on ios 11.2.6?. i have try give props isMobile but still failed domain url but already white list my web on callback. but in browser it's work?.

**Comment by Marcosul** [comment]
This is happening with my project. Works in desktop browser but does not work in mobile browser.

**Comment by thakurinbox** [comment]
@zanisis  @Marcosul Please follow the following:

You need to add two additional props in FacebookLogin.

 ```
isMobile={true}
disableMobileRedirect={true}
```
It will surely fix the issue.

**Comment by techyrajeev** [comment]
@thakurinbox can you please share your component details with props which you are passing?
