### ISSUE TITLE
How to do log out?

### ISSUE THREAD

**Issue by hitesh22feet** [keppelen/react-facebook-login#216]

**Comment by hectorhottomali** [comment]
There is a FB variable inside the window property.
Here is something I just did to logout:

`<a href="#" onClick={(e)=>{e.preventDefault(); window.FB.logout()}}>logout</a>`

Please check this part: `window.FB.logout()`

This function is the one that logs a user out of Facebook, you can call in inside another function like so:

`onLogout() {`
    `window.FB.logout()`
`}`

**Comment by morrigan** [comment]
@hectorhottomali any idea why this might not be working? My login status is still `connected`.

**Comment by hectorhottomali** [comment]
@morrigan No sorry, you can use the console log and see everything you have available on the window. console.log(window).
You can check if indeed you have the window.FB

**Comment by andycorm** [comment]
This doesn't seem to work, and throws an "init not called with valid version" error.
