### ISSUE TITLE
Cannot programmatically click component

### ISSUE THREAD

**Issue by JustinMoser** [keppelen/react-facebook-login#224]
Hi,
For various reasons, I need to be able to programmatically trigger the click event on the facebooklogin component, however doing it the usual way, like so:

```
class CustomClass extends Component {

    constructor(props){
        super(props);
        ...
        this._facebookClick = this._facebookClick.bind(this);
    }

    _facebookClick(){
        ...
        ...
        const domNode = ReactDOM.findDOMNode(this.facebookButton);
        domNode.click();
    }

    render() {

        <div id="custom-btn">
            <button type="button" class="fb-login-button"  onClick={this._facebookClick} />
        </div>

        <div style={{visibility: 'hidden'}}>
            <FacebookLogin
              ref={ (input) => { this.facebookButton = input } }
              appId={FACEBOOK_ID}
              autoLoad={false}
              fields="name,email,picture"
              onClick={ (ev) => { console.log("fb click event") } }
              callback={this.fbResponse}/>
        </div>
    }
}
```

I've tested and it definitely makes it into the `_facebookClick` method, and ReactDOM is correctly selecting the hidden facebookButton DOM element however, when it comes to calling `domNode.click();` nothing happens at all.

Any ideas? I am doing the same with another social login component (Google) and it works as expected.

Any suggestion for programmatically triggering the Facebook component's click function, and triggering the authentication window pop up?

Thanks,
Justin

**Comment by keppelen** [comment]
https://github.com/keppelen/react-facebook-login#facebook-button-without-styling

**Comment by JustinMoser** [comment]
@keppelen thank you, but the reason I need my own button and need to programatically click the facebook button is essentially because i need to pass the actual click behaviour of the facebooklogin component to another component, before the auth window gets triggered.

It is for GDPR, and essentially I need an extra window before the auth window appears, and then in that extra window (this is all implemented successfully btw). when they click a button trigger the facebook auth window / callback.

Justin
