### ISSUE TITLE
does not show Facebook login screen

### ISSUE THREAD

**Issue by patilrevansidh** [keppelen/react-facebook-login#228]
If I'm not logged into facebook. Then it should open popup and allow to enter credentials. But instead show error as 
`Not Logged In: You are not logged in. Please login and try again.`

![image](https://user-images.githubusercontent.com/11453641/41715856-580fc402-7572-11e8-85e2-53e8f362bc33.png)

**Comment by shr33narayan** [comment]
I second that!

**Comment by shr33narayan** [comment]
Also if you login with incognito after login to your facebook account, then you would be shown a sever problem, **[Insecure Login Blocked: You can't get an access token or log in to this app from an insecure page. Try re-loading the page as https://](https://stackoverflow.com/a/49419559)**. The thing is facebook is forcing and requiring the request from an https: (SSL) server.

The quick overcome of the **solution** if running from localhost is (if using create-react-app) is run by `HTTPS=true yarn start`. [This would enable](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#using-https-in-development) https in your localhost, and the problem may be resolved.

**Comment by PriyankaAshu** [comment]
Not Logged In: You are not logged in. Please login and try again.

Getting same......

**Comment by techyrajeev** [comment]
Any solution so far ?
I am also facing exactly same issue.

**Comment by shr33narayan** [comment]
@PriyankaAshu @techyrajeev try the suggestions I mentioned [above](https://github.com/keppelen/react-facebook-login/issues/228#issuecomment-401255794) Let me know if it worked.

**Comment by amcvitty** [comment]
I had the same issue just now and solved it by adding my site to the list of "Valid OAuth Redirect URIs" in the Facebook developers site https://developers.facebook.com/apps/ 

There is a setting there about enforcing HTTPS too, which is perhaps why it was relevant to @shr33narayan but I don't know for sure about that. 

I think Facebook could maybe do more to help people here in development, but I suspect they don't want to give away too much about the developers' security settings to users of the app
