### ISSUE TITLE
Response Type set to token even though 'code' is specified

### ISSUE THREAD

**Issue by alek5k** [keppelen/react-facebook-login#229]
Hello,

My component is mounted like this, explicitly setting the responseType:

```
<FacebookLogin
    appId={settings.facebookLoginClientId}
    autoLoad={false}
    fields="name,email,picture"
    icon="fa-facebook"
    onClick={this.loginClicked}
    textButton=""
    callback={this.responseFacebook}
    responseType="code"> 
</FacebookLogin>
```

However when I click the button, the popup window that comes up has the following signature for the GET request:

```
https://www.facebook.com/v2.3/dialog/oauth?
app_id=XXXX
&auth_type=
&channel_url=XXXX
&client_id=XXXX
&display=popup
&domain=XXX
&e2e=%7B%7D
&locale=en_US
&origin=1
&redirect_uri=XXXXX
&response_type=token%2Csigned_request
&return_scopes=false
&scope=public_profile%2Cemail
&sdk=joey
&version=v2.3
```

in my callback (this.responseFacebook above), I do not get a 'code' field, only an 'accessToken' field.

Your help figuring out why this is happening would be much appreciated.

**Comment by alek5k** [comment]
This seems to be because the plugin uses the Facebook Javascript SDK, which doesn't let you do server to server verification and instead passes you the authToken straight away (ie. uses an Implicit Flow rather than an Authorization Code Flow). I am closing this issue as it's not related to your code. Any ideas for getting access to the 'code' parameter to be able to implement Authorization Code Flow would be much appreciated.

**Comment by Microserf** [comment]
Have you had any luck @alek5k ? I am trying to do the same thing, and haven't had any luck getting anything other than the `accessToken` response.
