### ISSUE TITLE
HTTP will no longer work in 73 days

### ISSUE THREAD

**Issue by capttaz1** [keppelen/react-facebook-login#231]
I receive the subject of this line on every request. Will this be resolved soon?

**Comment by shyela** [comment]
This is probably not an issue with react-facebook-login. Facebook's "Enforce HTTPS" setting will be turned on for all FB apps in October. Code running on localhost will be exempted. See https://developers.facebook.com/blog/post/2018/06/08/enforce-https-facebook-login/

**Comment by RobertDeniszczyc** [comment]
Worth pointing out here if anyone stumbles on this with the same problem whilst using create-react-app you can run CRA locally with the HTTPS env variable set to true. Alongside enforcing HTTPS on your Facebook app this prevents this error/warning message from appearing. To use the env variable when you run npm start like add it in the command like so:
`HTTPS=true npm start`

**Comment by capttaz1** [comment]
Thank you Robert, perfect point

 

Thanks,

Rob
