### ISSUE TITLE
Unwanted query string appear when login on mobile

### ISSUE THREAD

**Issue by kykungz** [keppelen/react-facebook-login#235]
When I was at https://mywebsite.com and click login

My url changed to:
https://mywebsite.com/?code=xxxxxxx&state=facebookdirect#_=_&state=facebookdirect&scope=public_profile,email&response_type=code&return_scopes=false&auth_type&client_id=xxxxxxxx

So when I click login again, it shows that the redirect url is not allowed in my OAuth setting.

This behaviour happens only in mobile devices.

Here is how I use `react-facebook-login` (which is very normal)
```js
<FacebookLogin
    appId={config.FACEBOOK_APP_ID}
    autoLoad={false}
    fields="first_name,last_name,email,picture"
    callback={this.facebookResponse}
/>
```

**Comment by yugidazai** [comment]
@kykungz I also got this issue. Did you manage to fix it? Could you please share how you did that?

**Comment by tirli** [comment]
@kykungz Please, can you explain how you solved this issue? I have the same problem

**Comment by kykungz** [comment]
@tirli I haven't solved it, I use popup mode instead. From my understanding after looking for solutions, the extra strings are the intended behaviour of Facebook redirect.
