### ISSUE TITLE
Wrong App ID in Facebook url

### ISSUE THREAD

**Issue by gdpsysgarage** [keppelen/react-facebook-login#236]
Hi !! 

I have this block of code in my **js** file 

`import FacebookLogin from 'react-facebook-login/dist/facebook-login-render-props'`

```
<FacebookLogin
     appId="687661704929636"
     autoLoad={true}
     fields="name,email,picture"
     callback={this.responseFacebook}
     render={renderProps => (
            <button className="log-in-button facebook" onClick={renderProps.onClick}>
               <i className="fa fa-facebook" aria-hidden="true"></i>
               <span>Ingresar con Facebook</span>
             </button>
    )} />
```
But when I click on my button I am beeing redirected to 

`https://www.facebook.com/v2.12/dialog/oauth?app_id=218965718677864&auth_type=&channel_url=https%3A%2F%2Fstaticxx.facebook.com%2Fconnect%2Fxd_arbiter%2Fr%2FQX17B8fU-Vm.js%3Fversion%3D42%23cb%3Df385c8062ff8dbc%26domain%3Dlocalhost%26origin%3Dhttp%253A%252F%252Flocalhost%253A3000%252Ff254b3acaaabed%26relation%3Dopener&client_id=218965718677864&display=popup&domain=localhost&e2e=%7B%7D&fallback_redirect_uri=http%3A%2F%2Flocalhost%3A3000%2F&locale=en_US&origin=1&redirect_uri=https%3A%2F%2Fstaticxx.facebook.com%2Fconnect%2Fxd_arbiter%2Fr%2FQX17B8fU-Vm.js%3Fversion%3D42%23cb%3Df339ea03131404c%26domain%3Dlocalhost%26origin%3Dhttp%253A%252F%252Flocalhost%253A3000%252Ff254b3acaaabed%26relation%3Dopener%26frame%3Df314261b46e7c64&response_type=token%2Csigned_request&return_scopes=false&scope=public_profile%2Cemail&sdk=joey&version=v2.12`

Where the **app_id parameter is 218965718677864**

![captura de pantalla 2018-08-18 a la s 00 04 48](https://user-images.githubusercontent.com/37113788/44295173-617b9900-a27a-11e8-9bf4-97c6cd56bf93.png)

Why is happening this ?

Thanks

**Comment by leorcvargas** [comment]
Did you find out the solution? I'm having this problem

**Comment by Mattias37** [comment]
Same issue here
