### ISSUE TITLE
Allow customisation for locale for the Facebook sdk URL

### ISSUE THREAD

**Issue by lauterry** [keppelen/react-facebook-login#24]
Hello

The URL of the Facebook SDK is //connect.facebook.net/en_US/sdk.js with a hard coded local en_US

The react component should allow user to customize the locale.

Best regards.

**Comment by lauterry** [comment]
ok there is a pull request related to this issue. https://github.com/keppelen/react-facebook-login/pull/23

**Comment by keppelen** [comment]
@lauterry  :)

Tomorow new release

**Comment by lauterry** [comment]
Cool :)
