### ISSUE TITLE
Default version of FB SDK is outdated

### ISSUE THREAD

**Issue by sbolel** [keppelen/react-facebook-login#241]
### Summary

The default FB SDK version is outdated.

### Current Behavior

The [`defaultProps.version` is currently set to `v2.3`](https://github.com/keppelen/react-facebook-login/blob/master/src/facebook.js#L52). The [Facebook JavaScript reference][v3.1] no longer lists v2.3 of the SDK -- [v2.7][v2.7] is the oldest version listed. 

### Expected Behavior

The default FB SDK version should be changed to the latest, [v3.1][v3.1], if breaking changes don't have an impact. At a minimum, it should be updated to [v2.7][v2.7] so that users of this package can reference accurate docs.

[v2.7]: https://developers.facebook.com/docs/javascript/reference/v2.7
[v3.1]: https://developers.facebook.com/docs/javascript/reference/v3.1

**Comment by GustavoDinizMonteiro** [comment]
@sbolel I've seen that in the documentation is a version parameter with the purpose of defining the API version, have you already tested it ?

**Comment by sbolel** [comment]
@GustavoDinizMonteiro that's correct, it's one of the props:

```
      <FacebookLogin
       version="3.1"  // now we're using the latest version
        appId="1088597931155576"
        autoLoad={true}
        fields="name,email,picture"
        callback={this.responseFacebook}
      />
```

Which overrides [the `defaultProps.version`](https://github.com/keppelen/react-facebook-login/blob/master/src/facebook.js#L44):

```
  static defaultProps = {
    redirectUri: typeof window !== 'undefined' ? window.location.href : '/',
    scope: 'public_profile,email',
    returnScopes: false,
    xfbml: false,
    cookie: false,
    authType: '',
    fields: 'name',
    version: '2.3',   // this is outdated
    language: 'en_US',
    disableMobileRedirect: false,
    isMobile: getIsMobile(),
    onFailure: null,
    state: 'facebookdirect',
    responseType: 'code',
  };
```
...and that resolves the issue!

I feel like it would still be good to increase the _default version_ to one that is officially supported by facebook. It's easy to overlook the `version` prop  😅

**Comment by GustavoDinizMonteiro** [comment]
@sbolel oh yes, I agree with you, I was thinking that you were not able to change the version :sweat_smile: rsrsrs . I agree with you, so i'll make a pr for solve this :smile:.

**Comment by sbolel** [comment]
Awesome! :)

**Comment by GustavoDinizMonteiro** [comment]
This issue can be closed now

**Comment by sbolel** [comment]
Awesome work @GustavoDinizMonteiro! I closed the issue as your PR fixes it. Much appreciated.
