### ISSUE TITLE
Your thing doesn't call FB.init() ever.

### ISSUE THREAD

**Issue by TheImpressionist** [keppelen/react-facebook-login#243]
I have to do it manually to make it work.

The script is loaded only once, the configuration is:

```javascript
          <FBAuth
            appId="<app-id>"
            size="small"
            autoLoad={false}
            xfbml={true}
            fields="name,email,picture"
            icon="fa-facebook"
            callback={this.props.handleFacebookLogin}
          />
```

regardless if I set `autoLoad` to true or not, it does the same thing. Which is nothing.

So the grand error is: `FB.login() called before FB.init()`

**Comment by stevez86** [comment]
I'm also getting this issue

**Comment by joeythelantern** [comment]
Also getting rekt by this problem :(

**Comment by joeythelantern** [comment]
autoLoad={true} doesn't stop it

**Comment by angelxmoreno** [comment]
I am having the same issue. I confirmed my app_id is indeed being set as per https://github.com/keppelen/react-facebook-login/issues/71#issuecomment-408006509

**Comment by ajsharp** [comment]
I'm getting this too. This library should raise an error is appId is either null or an empty string.
