### ISSUE TITLE
scope didn't work

### ISSUE THREAD

**Issue by rahilahmad** [keppelen/react-facebook-login#247]
i set permissions in the scope but i didn't work

**Comment by rahilahmad** [comment]
Hi,
bro to enable scope other than default you have to get permission from the
facebook.
for this you go to : https://developers.facebook.com/ , select you app then
select app review and then add permissions you want to enable
after this you have to fill a form which will go the facebook
administration for reviewing you app

**Comment by asafam** [comment]
Was it resolved? I am having similar issues - my app has ads_management permission, but when I define scope="ads_management" the user does not have this permission. It seems to ignore my scope values
