### ISSUE TITLE
Facebook login doesn't work in PWA app with display standalone

### ISSUE THREAD

**Issue by garibyta** [keppelen/react-facebook-login#248]
I added my webapp to my mobile home screen (android device).
When I tried to facebook login, I got the permission window and authorized the app, but after clicking done it didn't return to my webapp (got white screen instead).

**Comment by garibyta** [comment]
The problem was in my facebook account, missing configuration: 
Valid OAuth Redirect URIs

**Comment by drsherlock** [comment]
I am facing the same issue, i redirect to the facebook login page from my pwa, but it just shows a blank screen.
Could you please share the facebooklogin component, so that I can check if I am doing anything differently?
