### ISSUE TITLE
How the icon property works ?

### ISSUE THREAD

**Issue by lauterry** [keppelen/react-facebook-login#25]
Hello

It's not clear how the `icon` property works ?

It's seems to need font-awesome right ?

Do we have to include it ourself ? If so, please mention it in the documentation.

Best regards

**Comment by Splact** [comment]
The component loads the font itself as you can see in [src/facebook.js](https://github.com/keppelen/react-facebook-login/blob/master/src/facebook.js#L88).

**Comment by lauterry** [comment]
Oh yeah

Haven't notice it

Sorry for the noise

**Comment by keppelen** [comment]
Thank you @Splact for show
