### ISSUE TITLE
Scope is not working

### ISSUE THREAD

**Issue by asafam** [keppelen/react-facebook-login#263]
The `ads_management` permission I defined in scope are not requested upon user login (and any other permissions):
```
import FacebookLogin from 'react-facebook-login';
```
```
render() {
    return (
        <FacebookLogin
            appId=<MY_APP_ID>
            autoLoad={true}
            fields="name,picture"
            scope="public_profile,email,ads_management" 
            onClick={this.onClick}
            callback={this.onFacebookResponse} />
    );
}
```
I tried it with users that have never used the app, and users that have previously approved the app.

I check it according to the user accessToken value and verify the token permissions with `https://graph.facebook.com/<VERSION>/me/permissions` facebook graph endpoint.

Please help!
Thanks in advance

**Comment by asafam** [comment]
P.S: I am also using a secured `https` connection

**Comment by birelian** [comment]
Same problem here. Thanks.
