### ISSUE TITLE
[Question] How do you show progress/loading spinner while page is logging in? 

### ISSUE THREAD

**Issue by henryhsue** [keppelen/react-facebook-login#268]
Anyone have a good example or tutorial provided with general purpose animation?

**Comment by janbarta** [comment]
@henryhsue  How did you solve it?

**Comment by matheusvellone** [comment]
@janbarta you can use "Facebook button without styling" section from readme to accomplish that.
Inside the `renderProps` there are a `isProcessing` prop that can help you on showing a loading spinner when the component is processing.
