### ISSUE TITLE
Button stucks at processing state when user close window

### ISSUE THREAD

**Issue by horaklukas** [keppelen/react-facebook-login#270]
I'm using the button in my web app and it works perfectly but I'm not able to open facebook window again once it's closed

Steps to reproduce
1. Click on the button => facebook login in new tab is opened
2. Close the browser tab
3. Click on the button => facebook login not opened again

I did a bit of debugging and found out that problem is `isProcessing` flag in button's state. Once the login window is closed, callback that should set `isProcessing` to `false` is not called and so the component gets stucked in that state forever.

I wasn't able to figure it out, don't you have any ideas? Was it working correctly in the past?

**Comment by KhorenGrig** [comment]
I also have same problem. Do you find a solution?

**Comment by horaklukas** [comment]
Unfortunately no 🙁

**Comment by horaklukas** [comment]
It stopped to happen without any change in source code 🤔now it works how it should so maybe it was a bug in FB sdk.

**Comment by markotom** [comment]
It's happening with mobile redirect enabled, login in the same window. Once facebook login is displayed and you navigate backward to your app, button stucks at processing state.
