### ISSUE TITLE
render props doesnt exist in version 4.1.1

### ISSUE THREAD

**Issue by soylemezali42** [keppelen/react-facebook-login#273]
I cant find render function for FacebookLogin component.  Also, icon props doesn't work properly,  when i add "fab fa-facebook-f" fontawesome icon class. The Component renders "fa fab fa-facebook-f" class on <i> dom element.

**Comment by VapiSoft** [comment]
I also cannot compile it because of the
`render={renderProps => `

**Comment by RakelO** [comment]
@soylemezali42 use proper import

```
import FacebookLogin from 'react-facebook-login/dist/facebook-login-render-props'
```

**Comment by CAIJIN1002** [comment]
> @soylemezali42 use proper import
> 
> ```
> import FacebookLogin from 'react-facebook-login/dist/facebook-login-render-props'
> ```

I tried this solution, but it shows
```
Could not find a declaration file for module 'react-facebook-login/dist/facebook-login-render-props'. '/Users/username/node_modules/react-facebook-login/dist/facebook-login-render-props.js' implicitly has an 'any' type.
  If the 'react-facebook-login' package actually exposes this module, consider sending a pull request to amend 'https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-facebook-login`ts(7016)
```

**Comment by arunsingh28** [comment]
same issue with me...

**Comment by dexkode4** [comment]
same issue here

**Comment by ThibaudMoretto** [comment]
Same here

**Comment by GO-Lorenzo** [comment]
Same issue
