### ISSUE TITLE
Possible duplicate for Font Awesome (cause in-component loading)

### ISSUE THREAD

**Issue by Splact** [keppelen/react-facebook-login#29]
It is safe to load Font Awesome directly inside the component without any check? There is a way to say "Hey, I've Font Awesome already loaded"?

There is some browser logic (other than file cache) that makes this double (or more) loading negligible?

**Comment by citizen-stig** [comment]
Yes, for example I already have a font awesome loaded and I don't to do another server request

**Comment by keppelen** [comment]
@Splact  @citizen-stig  what do you think, if you pass `fontAwesome` the componente loaded the `css`, but default is `true`

```js
<FacebookLogin
    icon="fa fa-facebook"
    appId={this.state.fb_id}
    callback={this._onFBResponse}
    fontAwesome={false}
/>
```

**Comment by citizen-stig** [comment]
@keppelen, yes sounds good, but maybe name for parameter might be a "loadFontAwesome".

**Comment by crisys11** [comment]
I open a pull request to solve this https://github.com/keppelen/react-facebook-login/pull/61

**Comment by keppelen** [comment]
https://github.com/keppelen/react-facebook-login/pull/61
