### ISSUE TITLE
Facebook login button is not working

### ISSUE THREAD

**Issue by atopdev** [keppelen/react-facebook-login#293]
I integrated react-facebook-login module for logging users into the app.

But when I open the site through **Facebook in-app browser**, it is not working.

This is the top priority issue for our customers since we are advertising the app through Facebook.

Could you check this issue asap?

Thanks.

**Comment by shannonnolan17** [comment]
We are having the same issue here!

**Comment by hieusmiths** [comment]
Me too.

I don't know this library have support along.
With login by web desktop browser it well.
But if  using it for login with web mobile application it will return errorr like bellow:

URL  prevent: progress this redirect not working becasue this redirect URL not avaible in list URL valid in the setting OAuth.

Thank so much.

**Comment by daveteu** [comment]
have u guys tried disableMobileRedirect={true} ?

**Comment by keppelen** [comment]
Exact, you can disable mobile redirect or configure this url in Facebook Apps

**Comment by shannonnolan17** [comment]
Tried that and it didn't work. Why is this closed?

**Comment by mrgiacomini** [comment]
it's happening to me too, I tried the solutions that have already reported and it still didn't work

**Comment by ronytesler** [comment]
Has someone solved it?
