### ISSUE TITLE
Facebook login button doesn't able to load SDK

### ISSUE THREAD

**Issue by DenisDiachenko** [keppelen/react-facebook-login#325]
We integrated the facebook-login-button into our projects, but today it stopped working for unknown reasons.
I use `FacebookLogin` from `react-facebook-login/dist/facebook-login-render-props` and see `isSdkLoaded` always `false`.
What happened here?

**facebook-login-button**: ^4.1.1,
**react**: "^16.13.1",

**UPDATE**: https://developers.facebook.com/status/issues/492652922187445/
Thanks @sneakersgames for update

**Comment by cauebarreira** [comment]
We are facing the same problem here.

**Comment by abStack-pk** [comment]
Same issue

**Comment by fjuriolli** [comment]
Same thing here

**Comment by phbernard** [comment]
I can see:

![image](https://user-images.githubusercontent.com/423852/116699676-2425ae00-a9c6-11eb-9759-b5a893f02e4d.png)

The second call is strange. Once decoded, the URL is:

    https://www.facebook.com/common/scribe_endpoint.php?c=jssdk_error&m={"error":"LOAD", "extra": {"name":"Error","line":"undefined","script":"undefined","stack":"Error: Module FB has not been defined
        at j (https://connect.facebook.net/en_US/sdk.js?hash=3cf0af522fc202707998ff1ffe40f989&ua=modern_es6:24:295)
        at k (https://connect.facebook.net/en_US/sdk.js?hash=3cf0af522fc202707998ff1ffe40f989&ua=modern_es6:24:977)
        at Object.<anonymous> (https://connect.facebook.net/en_US/sdk.js?hash=3cf0af522fc202707998ff1ffe40f989&ua=modern_es6:47:61)
        at j (https://connect.facebook.net/en_US/sdk.js?hash=3cf0af522fc202707998ff1ffe40f989&ua=modern_es6:24:793)
        at k (https://connect.facebook.net/en_US/sdk.js?hash=3cf0af522fc202707998ff1ffe40f989&ua=modern_es6:24:977)
        at Object.n [as __d] (https://connect.facebook.net/en_US/sdk.js?hash=3cf0af522fc202707998ff1ffe40f989&ua=modern_es6:24:1294)
        at Object.<anonymous> (https://connect.facebook.net/en_US/sdk.js?hash=3cf0af522fc202707998ff1ffe40f989&ua=modern_es6:47:1)
        at https://connect.facebook.net/en_US/sdk.js?hash=3cf0af522fc202707998ff1ffe40f989&ua=modern_es6:186:452
        at https://connect.facebook.net/en_US/sdk.js?hash=3cf0af522fc202707998ff1ffe40f989&ua=modern_es6:186:467","revision":"1003714696","namespace":"FB","message":"Module FB has not been defined"}}

**Comment by alshakero** [comment]
I'm getting the same thing with vanilla FB SDK. Doesn't seem to be an RFL issue.

**Comment by romatallinn** [comment]
I'm not sure regarding SDK, but the button visually looks disabled for me. Is this the problem for others as well?

**Comment by sneakersgames** [comment]
Issue @ Facebook; follow the status here: https://developers.facebook.com/status/issues/492652922187445/

**Comment by maitzeth** [comment]
same here :'( now im waiting

**Comment by maitzeth** [comment]
> I'm not sure regarding SDK, but the button visually looks disabled for me. Is this the problem for others as well?

same here, yesterday was working perfectly

**Comment by Stavya1993** [comment]
> I'm not sure regarding SDK, but the button visually looks disabled for me. Is this the problem for others as well?

Yes, facing the same issue for the last couple of hours. Have a bunch of users who arent able to use the app!

**Comment by akshaybande81** [comment]
same issue.

**Comment by arielhernandezmusa** [comment]
Same issuse here

**Comment by arturhaddad** [comment]
Relieved to know it's not only here

**Comment by yg-yash** [comment]
Same Issue
Tried two sdks

**Comment by ibrahimyaacob92** [comment]
same issue.. cannot login !!!

**Comment by kisstamasj** [comment]
same issue, it seems like thee button is disabled, and I can'1t click on it.

**Comment by cauebarreira** [comment]
Apparently, it's working again here.

**Comment by arturhaddad** [comment]
It's working again here too

**Comment by kisstamasj** [comment]
it's working for me too.

**Comment by DenisDiachenko** [comment]
Issue resolved by Fscebook team
