### ISSUE TITLE
FB.* is not a function!

### ISSUE THREAD

**Issue by rsflow** [keppelen/react-facebook-login#45]
Hi,

I get `FB.login is not a function` or `FB.getLoginStatus is not a function`. The `FB.api` doesn't give this error but it doesn't produce any response either.

Thank You!

**Comment by cauealves** [comment]
Hello, @rsflow 

Do you have any extension of your browser that may be blocking the request?

**Comment by rsflow** [comment]
Hey @cauealves you are a genius,
It was AdBlock ... never expected it.
Thank you again :)

**Comment by cauealves** [comment]
You're welcome. Glad you could 💃 💃
