### ISSUE TITLE
Fb logout

### ISSUE THREAD

**Issue by alexhawkins** [keppelen/react-facebook-login#54]
Great work here. How would i go about setting up Logout?

**Comment by ammichael** [comment]
I store the login data in localstorage, and when the user logout, I just clean it up. It's working for me, but I'm not sure if there is a better way (or better practice?)

**Comment by keppelen** [comment]
@alexhawkins logout only facebook website.

**Comment by dmkboo** [comment]
@ammichael did you store the whole response, or how did you did it?

**Comment by ammichael** [comment]
@dmkboo I just stored the data I needed, in the structure that makes more sense for me. But I don't think it would be a problem to store the whole response..

**Comment by francisrod01** [comment]
Well, after logged, every time I refresh the page, facebook make a login automatically because the app is allowed already. So.. clean localstorage don't solve anything here.

**Comment by francisrod01** [comment]
The pull request is it: https://github.com/keppelen/react-facebook-login/pull/34

**Comment by tylerj** [comment]
I landed on this issue because even when a user logs out of my application, visiting the page that includes the `FacebookLogin` component will automatically log them back in.

The solution for me was to change the `autoLoad` prop on the `FacebookLogin` component to `false` (or remove this prop, as the default is `false`), requiring the use to click the login button again.

**Comment by rjnsalvador** [comment]
@tylerj Hi Sir, that's what I do as well, however, once the user hits the login button again, it will automatically login the previous account that was used. For my use case, I'd like the user to enter the credentials after hitting login button.

**Comment by GuyoST** [comment]
Hello, yes same problem here, when the user click again on the Facebook button, it's logged automatically without asking anything, not convenient if another user wants to login.

**Comment by RemyMachado** [comment]
It's a shame that we can't log out other than by going to the Facebook website. It's losing a lot of its interest.

**Comment by horlard** [comment]
> It's a shame that we can't log out other than by going to the Facebook website. It's losing a lot of its interest.

really annoying

**Comment by InnovexIT-Syl** [comment]
> It's a shame that we can't log out other than by going to the Facebook website. It's losing a lot of its interest.

Very annoying.This is the worst library i ever used.

**Comment by ujjwal-shrivastava** [comment]
Why there is not Fb log out function please work on it n release it or give the solution here
