### ISSUE TITLE
Specify desired HTML tag as a prop

### ISSUE THREAD

**Issue by alfredoreduarte** [keppelen/react-facebook-login#62]
Wouldn't it be good to be able to indicate the HTML tag? Like, if you want the result to be an `<a>` instead of a `<button>`

**Comment by crisys11** [comment]
What is the reason for replace the tag?

**Comment by alfredoreduarte** [comment]
e.g: someone wants to ask registered users for a specific extra permission, using a link instead of a button

**Comment by crisys11** [comment]
Is not implicit in documentation but you can do it send "scope" property, i will open a pull request to expecifi this in documentation :)

the component send the url in this way

`https://www.facebook.com/dialog/oauth?client_id=${appId}&redirect_uri=${window.location.href}&state=facebookdirect&${scope}`

**Comment by alfredoreduarte** [comment]
I'm sorry, perhaps I'm not being clear enough. I mean specifying the desired html tag, like using a `<a>` instead of a `<button>`.

I mentioned extended permissions as an example because you might want a big ass login button, and then a small link for extra permissions that might be needed inside of an app.

**Comment by bertho-zero** [comment]
https://github.com/keppelen/react-facebook-login/issues/66#issuecomment-245633941

**Comment by tristant** [comment]
Same here, would very much like to be able to choose what kind of HTML tag. Also the block of styles that is created afterwards shouldn't be a default.

**Comment by bertho-zero** [comment]
Indeed, this component is not generic, I made it reusable in my project:

- choose your component
- no default style
- fix fb-root duplication
- remove useless dependencies (font-awesome..)
- no autocall '/me' to Facebook API after login

https://github.com/bertho-zero/react-redux-universal-hot-example/blob/progressive/src/components/FacebookLogin/FacebookLogin.js

**Comment by goldylucks** [comment]
@bertho-zero is your implementation still around?
the link u provided is dead :(

**Comment by bertho-zero** [comment]
@goldylucks I just updated the link.

**Comment by arabold** [comment]
Thanks for this. This is super useful and should be a pull request IMO!

**Comment by arabold** [comment]
Created a super-simple Pull Request for this which allows you to completely customize how the Facebook login is rendered: https://github.com/keppelen/react-facebook-login/pull/107
