### ISSUE TITLE
textButton props should accept React.PropTypes.element

### ISSUE THREAD

**Issue by lauterry** [keppelen/react-facebook-login#66]
Hi

I got the following warning : 

```
 Failed propType: Invalid prop `textButton` of type `object` supplied to `t`, expected `string`.
```

It is because I use react-intl to give the `textButton` props value :  

```
<FacebookLogin
        textButton={ <FormattedMessage
            id="auth.facebook.login.button.label"
            description="Facebook login button label"
            defaultMessage="Login with Facebook"/> }
    />
```

I think textButton props should also accept React.PropTypes.element : 

```
textButton: React.PropTypes.oneOfType([
        React.PropTypes.string,
        React.PropTypes.element
    ])
```

Best regards

**Comment by bertho-zero** [comment]
You can look my [FacebookLogin.js](https://github.com/bertho-zero/react-redux-universal-hot-example/blob/social-login/src/components/FacebookLogin/FacebookLogin.js) and its use [here (line 37 & 51)](https://github.com/bertho-zero/react-redux-universal-hot-example/blob/social-login/src/containers/Login/Login.js#L37), it's a fork of this repo with just the essentials and the ability to use a custom component.

You can use it like this, first your custom button:
```js
FacebookLoginButton = ({ facebookLogin }) =>
  <button onClick={facebookLogin}>
    <FormattedMessage
      id="auth.facebook.login.button.label"
      description="Facebook login button label"
      defaultMessage="Login with Facebook"/>
  </button>;
```

and the FacebookLogin component:

```js
<FacebookLogin
  appId="619121718248110"
  /* autoLoad={true} */
  fields="name,email,picture"
  callback={this.onFacebookLogin}
  component={this.FacebookLoginButton}
/>
```
