### ISSUE TITLE
strange error "Cannot read property 'login' of undefined(…)"

### ISSUE THREAD

**Issue by optimatex** [keppelen/react-facebook-login#72]
Hi. Sometimes i get this error. Error is located here `window.FB.login(r.checkLoginState`. So, i supposed it appears when FB scripts didn't finish loading. When i give it more time and push login button after 30 sec it definetly works correct.
How can i avoid this? maybe i can prevent callback execution until it finish loading?
and thanks for cood project

**Comment by grandmore** [comment]
@optimatex I have exactly the same issue. Did you find a fix?

Thanks,

**Comment by optimatex** [comment]
@grandmore unfortunaly no. But i have a primitive idea - i put callback function into setTimeout(). So, when user click on "signin with facebook" - callback will be executed after certain time. I didn't test this solution cuz it's hard to catch this error. But i supposed that this error appears because of uploading FB scripts haven't been complete.

**Comment by gocamille** [comment]
I have the same error, and it doesn't seem as though it's loading this file: 

```facebook-login.js:1GET https://connect.facebook.net/en_US/all.js ``` on `componentDidMount`.

I'll have to switch plugins in order to continue at the moment 🤕

**Comment by optimatex** [comment]
@gocamille what u mean when you say

> I'll have to switch plugins in order to continue at the moment
