### ISSUE TITLE
No cookie is set

### ISSUE THREAD

**Issue by jonasostrom** [keppelen/react-facebook-login#73]
Login works perfect but there is no cookie set for my php-script to fetch after callback?

version 3.4.0

```
<FacebookLogin
          appId="{}"
          autoLoad={false}
          cookie={true}
          scope='public_profile,email,user_friends'
          fields="name,email,picture"
          onClick={this.getCurrentUser}
          icon="fa-facebook"
          callback={this.props.store.loginWithFacebook} 
/>
```

SOLVED!
I found that chrome does not accept cookies on localhost. It all worked in firefox.

**Comment by jonasostrom** [comment]
Maybe this is a localhost problem, anyway to work around that?

**Comment by keppelen** [comment]
You set cookie on Ajax response in `callback component`. That responsibility is do not of component :)
