### ISSUE TITLE
"Sorry, something went wrong" on facebook dialog window

### ISSUE THREAD

**Issue by aasilva** [keppelen/react-facebook-login#75]
After click on login component the facebook dialog window is opened and show this message:

"
Sorry, something went wrong.

We're working on getting this fixed as soon as we can.

Go Back
"

Anyone knows what's wrong?

thanks

![fb_screen_shot](https://cloud.githubusercontent.com/assets/10654343/20215631/80eae93a-a80d-11e6-9ae8-3196c08e039e.png)

**Comment by goldylucks** [comment]
If memory serves, this happens if your fb app isn't configured properly.
can u share your (non secret) configuration?

**Comment by felixhagspiel** [comment]
I am also getting this error when developing locally.
"App Domains" contains `localhost`, "Site URL" contains `http://localhost:3000/`. I tried it with a CORS plugin, but still no luck. If I am not logged in, the login screen displays properly. Could this be a http vs https problem?

**Comment by tzookb** [comment]
any ideas on this one?
getting the same error 3 years later :)

**Comment by weherr** [comment]
According to this [https://stackoverflow.com/questions/22889646/fb-getloginstatus-returns-status-unknown](https://stackoverflow.com/questions/22889646/fb-getloginstatus-returns-status-unknown) it can happen when chrome is blocking third party cookies.

When I was testing using an incognito mode tab and it did not work--switched to a regular tab and it worked fine.
