### ISSUE TITLE
Only load the FB icon from font-awesome

### ISSUE THREAD

**Issue by goldylucks** [keppelen/react-facebook-login#77]
@keppelen I can do most of the work, might need a small touchup on webpack at the end.

should I prepare a PR?

**Comment by keppelen** [comment]
@goldylucks yep 😄

**Comment by mrhandoko** [comment]
when I make fb login custom element according to your documentation. I met this error. How to fix this?

`Warning: Failed prop type: Calling PropTypes validators directly is not supported by the `prop-types` package. Use PropTypes.checkPropTypes() to call them. `

And code goes here
```
import React from 'react'
import FacebookLogin from 'react-facebook-login'

const responseFacebook = response => {
  console.log(response)
}

const FBLogin = () => (
  <div>
    <FacebookLogin
      appId="765358716970952"
      autoLoad={true}
      fields="name,email,picture"
      callback={responseFacebook}
      icon="fa-facebook"
    />
  </div>
)

export default FBLogin
```

**Comment by advance512** [comment]
@goldylucks - did you ever submit the PR?

**Comment by goldylucks** [comment]
Nope.
Didn't get a response so I ditched this :)

**Comment by advance512** [comment]
That sucks :(

**Comment by goldylucks** [comment]
if memory serves, someone mentioned an alternative he made, without loading all font awesome.
Search this repo u might find it :)

**Comment by leedongwei** [comment]
Here: https://github.com/iliran11/facebook-login-redux-react
