### ISSUE TITLE
Make demo on github pages

### ISSUE THREAD

**Issue by goldylucks** [keppelen/react-facebook-login#79]
The purpose of the demo is to let developers test quickly the package without downloading it

I can add an after_success script that will build latest master and push it to gh-pages

The demo will be a simple page with inputs for all the props the button supports

@keppelen what r your thoughts?

**Comment by keppelen** [comment]
@goldylucks i thins is good, you can send a pr?

**Comment by goldylucks** [comment]
Sure can
expect it in the next few days

**Comment by goldylucks** [comment]
@keppelen I'll make it once #80 is resolved
