### ISSUE TITLE
Should add a feature to return the original response object received

### ISSUE THREAD

**Issue by afsheenirani** [keppelen/react-facebook-login#83]
Hi @keppelen - Firstly, its really great that you have built this react FB login component. 
Well, the issue I'm raising is two-fold:
1. The documentation today does not clearly define what is the response received by the callback 'responseFacebook'. Looking at the underlying code, I see it is either the response.status if it is a failed login attempt OR then it is a new object of the result of the "me" combined with response.authResponse.
2. It's great that you have provided your custom implementation to handle those responses but if someone is building their own login flows and maintaining their own state in using redux, it can be limiting in some ways as they would need the original response object received from the actual FB.getLoginStatus() call. Having said that, can a new boolean prop (say) "origResponse" be added to the component in order to simply return the original response object so the user can do their own login state management?

**Comment by lizlove** [comment]
Hi @keppelen @afsheenirani:
Just wanted to second this request for the option to return the original object. 
Thanks
