### ISSUE TITLE
Error: 'undefined is not a function', on chrome 36

### ISSUE THREAD

**Issue by neerav-mehta-olx** [keppelen/react-facebook-login#85]
On chrome version 36, 38, 39, getting an error, "undefined is not a  function" and callback is not getting called.
This error occurs after login into facebook.
Looking at the issue it seems like it is not able to find the callback function when it is already defined.
It is working fine on new chrome versions, 50,51,52,54

<FacebookLogin
textButton="LOGIN WITH FACEBOOK"
cssClass="tUpper action-button"
icon="fa-facebook-official"
appId={Application.settings.facebookAppId}
autoLoad={false}
fields="name,email,picture"
callback={this.responseFacebook.bind(this)}
onFailure={function(error) {
 console.log('error '+ error);
}
}
 />`

**Comment by keppelen** [comment]
@neerav-mehta-olx 
```jsx
<FacebookLogin
  textButton="LOGIN WITH FACEBOOK"
  cssClass="tUpper action-button"
  icon="fa-facebook-official"
  appId={Application.settings.facebookAppId}
  autoLoad={false}
  fields="name,email,picture"
  callback={this.responseFacebook}
  onFailure={(error) => console.log(`error ${error}`) }
/>
```
