### ISSUE TITLE
Getting username of logged in user.

### ISSUE THREAD

**Issue by HarshaVardhanPVK** [keppelen/react-facebook-login#87]
Hi, I am able to get userid, name, email, profile picture of user, which is pretty good. Is there any way to get username also of the logged in facebook user. Or please suggest me the best way to get username of the logged in user.

**Comment by RobertSheaO** [comment]
The username field was removed from the Facebook API 2 years ago. The fields this module accepts are the same that you can find in the [graph api explorer](https://developers.facebook.com/tools/explorer/) of the [Facebook developer's dashboard](https://developers.facebook.com).
