### ISSUE TITLE
Why the button is wrapped inside span tags?

### ISSUE THREAD

**Issue by ankitrg** [keppelen/react-facebook-login#88]
I am trying to use this login and it works fine, except for the fact that my styling breaks, due to `span`, is there a reason to use span?
moreover is there a way so that I can just export the `click` method and use it with any button as I see fit?

**Comment by joeyfigaro** [comment]
> is there a way so that I can just export the `click` method

This would be great. Currently no good way to apply project's existing styles for buttons.

**Comment by rolandokaizer** [comment]
Yeah, this span is really annoying

**Comment by jackfranklin** [comment]
@keppelen how would you feel about a PR that added a render prop ?

Then people could use this component like they can now:

```
<ReactFacebook ...><div>my custom btn</div></ReactFacebook>
```

And have the extra `span` wrapped around it.

But they could do:

```
<ReactFacebook render={(onClick) => <div onClick={onClick}>my custom btn</div>} />
```

And then not have to have the span around it. I'd be happy to work on this PR as it would help us :)

**Comment by corydeppen** [comment]
Looks like #182 suggests the `render` prop idea as well. Would definitely be helpful.
