### ISSUE TITLE
Different behavior in mobile

### ISSUE THREAD

**Issue by jonasostrom** [keppelen/react-facebook-login#89]
Hi, my login works perfect when sign in through a desktop browser. But on mobile device it's redirects with url with tokens, my js-callback is never triggered.

**Comment by jonasostrom** [comment]
Could it be a preventDefault(); ?

**Comment by leonmak** [comment]
I think there was a pr that solved this alr

**Comment by keppelen** [comment]
@leonmak thank :)

**Comment by Snabel** [comment]
@keppelen I need this feature in our production environment, could you update NPM anytime soon?

**Comment by alexhawkins** [comment]
@keppelen we need this feature in our production environment as well, could you update NPM anytime soon?

**Comment by mattmiddlesworth** [comment]
@keppelen noticed the latest source fixes this issue which we have as well, will there be a release soon? Thank you!

**Comment by keppelen** [comment]
@Snabel @alexhawkins @mattmiddlesworth New version in production https://www.npmjs.com/package/react-facebook-login

**Comment by mattmiddlesworth** [comment]
Confirmed this fixes issue, Thanks for the update! Have a great New Years
