### ISSUE TITLE
Error: Cannot resolve module 'React react'  in version 2.0.2

### ISSUE THREAD

**Issue by nguyenxuantruong** [keppelen/react-facebook-login#9]
I have just update new version ( 2.0.2) and get error.

ERROR in ./~/react-facebook-login/dist/facebook-login.js
Module not found: Error: Cannot resolve module 'React react' in **/node_modules/react-facebook-login/dist

**Comment by keppelen** [comment]
https://github.com/keppelen/react-facebook-login/commit/72c13f8fcb9ce02ed9c4f0824762cdc9a79d101d

**Comment by nguyenxuantruong** [comment]
thanks @keppelen, it works
